#!/bin/bash

echo "Shutting down containers"

docker-compose down
#docker stop $(docker ps -q)
#docker kill $(docker ps -q)
#docker rm $(docker ps -a -q)
#docker image rm $(docker image ls -a -q)

yarn unlink:clean:contracts
yarn unlink:subgraph
yarn unlink:dapp

echo "Removing data folder"

rm -rf data
